import { zodResolver } from "@hookform/resolvers/zod";
import { useState } from "react";
import { Controller, useForm, useWatch } from "react-hook-form";
import { useNavigate, useParams } from "react-router-dom";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { useIssue } from "@/features/tasks/api/get-issue";
import { useResolveIssue } from "@/features/tasks/api/resolve-issue";
import { useTask } from "@/features/tasks/api/get-task";
import { issueResolveSchema, type IssueResolveInput } from "@/features/tasks/types";
import { ApiError } from "@/lib/api-client";

// PRD §2.7/§4.3: Owner resolves a raised issue one of three ways (clarify / adjust deadline /
// reassign) — same "one form, branch on outcome" shape as OwnerTaskReviewPage's three-way review,
// mirrored deliberately since backend/app/crud.py's resolve_issue converges its reassign path
// through the exact same _reassign_task as review_task (DATA_MODEL.md's stated convergence).
export function IssueResolutionPage({
  employeeOptions,
}: {
  employeeOptions: { id: string; label: string }[];
}) {
  const { issueId } = useParams<{ issueId: string }>();
  const navigate = useNavigate();
  const { data: issue, isPending: issuePending, isError: issueError } = useIssue(issueId ?? "");
  const { data: task } = useTask(issue?.taskId ?? "");
  const resolveIssue = useResolveIssue();
  // Same "one key per navigated-to issue" shape as OwnerTaskReviewPage's idempotencyKey — a lazy
  // useState initializer, regenerated by the route wrapper keying this component on issueId
  // (router.tsx), not a useMemo the exhaustive-deps rule would flag for the same reason.
  const [idempotencyKey] = useState(() => crypto.randomUUID());
  const {
    register,
    handleSubmit,
    control,
    formState: { errors },
  } = useForm<IssueResolveInput>({
    resolver: zodResolver(issueResolveSchema),
    defaultValues: { resolutionType: "clarified" },
    // Without this, react-hook-form keeps a conditionally-rendered field's value in form state
    // after its input unmounts (a well-known RHF default, not a bug in RHF itself) — found by the
    // blind-authored test suite (2026-09-13): fill the deadline while on "Adjust deadline", switch
    // to "Clarify", submit — the stale deadline stayed in form state, tripped issueResolveSchema's
    // own combination guard (correctly, per the PRD's "only notes is valid for clarified" rule),
    // and silently blocked submission with no visible error (the missing errors.resolutionType
    // render below compounded it). shouldUnregister clears an abandoned branch's fields on unmount
    // instead, matching user intent instead of requiring them to notice and manually clear it.
    shouldUnregister: true,
  });
  const resolutionType = useWatch({ control, name: "resolutionType" });

  if (!issueId) return null;
  if (issuePending) return <p className="text-sm text-(--color-ledger-text-muted)">Loading…</p>;
  if (issueError || !issue) {
    return <p className="text-sm text-(--color-ledger-danger)">Could not load this issue.</p>;
  }

  async function onSubmit(input: IssueResolveInput) {
    if (!issueId) return;
    try {
      await resolveIssue.mutateAsync({ issueId, idempotencyKey, ...input });
      navigate("/");
    } catch {
      // resolveIssue.isError/.error already reflects this — rendered below.
    }
  }

  const errorMessage =
    resolveIssue.error instanceof ApiError && resolveIssue.error.status === 409
      ? "This issue has already been resolved — refresh and check again"
      : resolveIssue.error instanceof ApiError && resolveIssue.error.status === 422
        ? "The chosen assignee is not an active employee of this firm"
        : resolveIssue.isError
          ? "Something went wrong — try again"
          : null;

  return (
    <div className="flex flex-col gap-6">
      <h1 className="text-2xl">{task?.title ?? "Issue"}</h1>
      <p className="text-sm text-(--color-ledger-text-muted)">{issue.description}</p>
      <form onSubmit={handleSubmit(onSubmit)} className="flex flex-col gap-4">
        <div>
          <Label htmlFor="resolutionType">Resolution</Label>
          <Controller
            control={control}
            name="resolutionType"
            render={({ field }) => (
              <Select value={field.value} onValueChange={field.onChange}>
                <SelectTrigger id="resolutionType">
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="clarified">Clarify</SelectItem>
                  <SelectItem value="deadline_adjusted">Adjust deadline</SelectItem>
                  <SelectItem value="reassigned">Reassign</SelectItem>
                </SelectContent>
              </Select>
            )}
          />
          {errors.resolutionType && (
            <p className="mt-1 text-sm text-(--color-ledger-danger)">
              {errors.resolutionType.message}
            </p>
          )}
        </div>
        <div>
          <Label htmlFor="resolutionNotes">Notes</Label>
          <Input id="resolutionNotes" {...register("resolutionNotes")} />
          {errors.resolutionNotes && (
            <p className="mt-1 text-sm text-(--color-ledger-danger)">
              {errors.resolutionNotes.message}
            </p>
          )}
        </div>
        {resolutionType === "deadline_adjusted" && (
          <div>
            <Label htmlFor="newDeadline">New deadline</Label>
            <Input id="newDeadline" type="date" {...register("newDeadline")} />
            {errors.newDeadline && (
              <p className="mt-1 text-sm text-(--color-ledger-danger)">{errors.newDeadline.message}</p>
            )}
          </div>
        )}
        {resolutionType === "reassigned" && (
          <>
            <div>
              <Label htmlFor="remainingWorkDescription">Remaining work</Label>
              <Input id="remainingWorkDescription" {...register("remainingWorkDescription")} />
              {errors.remainingWorkDescription && (
                <p className="mt-1 text-sm text-(--color-ledger-danger)">
                  {errors.remainingWorkDescription.message}
                </p>
              )}
            </div>
            <div>
              <Label htmlFor="assignedTo">Reassign to (optional)</Label>
              <Controller
                control={control}
                name="assignedTo"
                render={({ field }) => (
                  <Select value={field.value} onValueChange={field.onChange}>
                    <SelectTrigger id="assignedTo">
                      <SelectValue placeholder="Keep current assignee" />
                    </SelectTrigger>
                    <SelectContent>
                      {employeeOptions.map((option) => (
                        <SelectItem key={option.id} value={option.id}>
                          {option.label}
                        </SelectItem>
                      ))}
                    </SelectContent>
                  </Select>
                )}
              />
              {errors.assignedTo && (
                <p className="mt-1 text-sm text-(--color-ledger-danger)">
                  {errors.assignedTo.message}
                </p>
              )}
            </div>
          </>
        )}
        {errorMessage && <p className="text-sm text-(--color-ledger-danger)">{errorMessage}</p>}
        <Button type="submit" disabled={resolveIssue.isPending}>
          {resolveIssue.isPending ? "Saving…" : "Resolve issue"}
        </Button>
      </form>
    </div>
  );
}
